import pandas as pd
import numpy as np

from typing import Optional, List
from .base import OutlierHandlerBase
from ..exceptions import HandlingException

# -----------------------------------------------------------------
#                       mean
# -----------------------------------------------------------------

class MeanHandler(OutlierHandlerBase):

    def __init__(self, columns: Optional[List[str]] = None):
        super().__init__(method = self.__class__.__name__, columns = columns)

    def apply(self, df: pd.DataFrame, outlier_mask: Optional[pd.DataFrame] = None) -> pd.DataFrame:
        """
        Replaces outliers with the column mean.
        """

        self._validate_input(df)

        if outlier_mask is None:
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = f"The 'mean' method requires an outlier mask generated by a detector."
            )
        
        if not df.index.equals(outlier_mask.index):
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = "Index mismatch: DataFrame and outlier_mask must have the same index."
            )
        
        df_clean = df.copy()

        if self.columns is None:
            raise RuntimeError("Validation was done, but self.columns remains None")
        
        for col in self.columns:
            if col in outlier_mask.columns:
                outliers = outlier_mask[col]

                if not outliers.any():
                    continue

                series_for_mean = df_clean[col].copy()
                series_for_mean[outliers] = np.nan

                replacement_val = series_for_mean.mean()

                if pd.isna(replacement_val):
                    raise HandlingException(
                        error_code = "HEX002",
                        method = self.__class__.__name__,
                        suggestion = f"Cannot compute mean for column '{col}'. All data points might be non-numeric or flagged as outliers."
                    )
                
                df_clean.loc[outliers, col] = replacement_val

        return df_clean



# -----------------------------------------------------------------
#                       median
# -----------------------------------------------------------------

class MedianHandler(OutlierHandlerBase):

    def __init__(self, columns: Optional[List[str]] = None):
        super().__init__(method = self.__class__.__name__, columns = columns)

    def apply(self, df: pd.DataFrame, outlier_mask: Optional[pd.DataFrame] = None) -> pd.DataFrame:
        """
        Replaces outliers with the column mean.
        """

        self._validate_input(df)

        if outlier_mask is None:
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = f"The 'mean' method requires an outlier mask generated by a detector."
            )
        
        if not df.index.equals(outlier_mask.index):
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = "Index mismatch: DataFrame and outlier_mask must have the same index."
            )
        
        df_clean = df.copy()

        if self.columns is None:
            raise RuntimeError("Validation was done, but self.columns remains None")
        
        for col in self.columns:
            if col in outlier_mask.columns:
                outliers = outlier_mask[col]

                if not outliers.any():
                    continue

                series_for_mean = df_clean[col].copy()
                series_for_mean[outliers] = np.nan

                replacement_val = series_for_mean.median()

                if pd.isna(replacement_val):
                    raise HandlingException(
                        error_code = "HEX002",
                        method = self.__class__.__name__,
                        suggestion = f"Cannot compute mean for column '{col}'. All data points might be non-numeric or flagged as outliers."
                    )
                
                df_clean.loc[outliers, col] = replacement_val

        return df_clean