import pandas as pd

from typing import Optional, List
from .base import OutlierHandlerBase
from ..exceptions import HandlingException, ConfigurationException

# -----------------------------------------------------------------
#                       mean
# -----------------------------------------------------------------

class ConstantHandler(OutlierHandlerBase):
    """
    Handler to replace outliers with a fixed, user-defined constant value.
    """

    def __init__(self, fill_value: float, columns: Optional[List[str]] = None):
        super().__init__(method = self.__class__.__name__, columns = columns)

        if not isinstance(fill_value, (int, float)):
            raise ConfigurationException(
                error_code = "CON004",
                method = self.__class__.__name__,
                parameter = "fill_value",
                suggestion = "The 'fill_value' must be a numeric (int or float) constant."
            )
        
        self.fill_value = fill_value

    def apply(self, df: pd.DataFrame, outlier_mask: Optional[pd.DataFrame] = None) -> pd.DataFrame:
        """
        Replaces outliers with the specified constant fill_value.
        """

        self._validate_input(df)

        if outlier_mask is None:
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = f"The 'mean' method requires an outlier mask generated by a detector."
            )
        
        if not df.index.equals(outlier_mask.index):
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = "Index mismatch: DataFrame and outlier_mask must have the same index."
            )
        
        df_clean = df.copy()
        replacement_val = self.fill_value

        if self.columns is None:
            raise RuntimeError("Validation was done, but self.columns remains None")

        for col in self.columns:
            if col in outlier_mask.columns:
                outliers = outlier_mask[col]

                if not outliers.any():
                    continue

                is_integer_dtype = pd.api.types.is_integer_dtype(df_clean[col].dtype)
                is_float_replacement = isinstance(replacement_val, float)

                if is_integer_dtype and is_float_replacement:
                    df_clean[col] = df_clean[col].astype(float)

                df_clean.loc[outliers, col] = replacement_val

        return df_clean