import pandas as pd
import numpy as np

from typing import Optional, List
from .base import OutlierHandlerBase
from ..exceptions import HandlingException


class InterpolateHandler(OutlierHandlerBase):

    def __init__(self, method: str = 'linear', columns: Optional[List[str]] = None):
        super().__init__(method = self.__class__.__name__, columns = columns)

        self.interpolation_method = method

    def apply(self, df: pd.DataFrame, outlier_mask: Optional[pd.DataFrame] = None) -> pd.DataFrame:
        """
        Replaces outliers with the column mean.
        """

        self._validate_input(df)

        if outlier_mask is None:
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = f"The 'interpolate' method requires an outlier mask generated by a detector."
            )
        
        if not df.index.equals(outlier_mask.index):
            raise HandlingException(
                error_code = "HEX001",
                method = self.__class__.__name__,
                suggestion = "Index mismatch: DataFrame and outlier_mask must have the same index."
            )
        
        df_clean = df.copy()

        if self.columns is None:
            raise RuntimeError("Validation was done, but self.columns remains None")
        
        for col in self.columns:
            if col in outlier_mask.columns:
                outliers = outlier_mask[col]

                if not outliers.any():
                    continue

                if pd.api.types.is_integer_dtype(df_clean[col].dtype):
                    df_clean[col] = df_clean[col].astype(float)


                series_to_fill = df_clean[col].copy()
                series_to_fill.loc[outliers] = np.nan

                filled_series = series_to_fill.interpolate(method = self.interpolation_method)     # type: ignore

                df_clean[col] = filled_series

        return df_clean