import pandas as pd

from typing import Optional, List
from .base import OutlierHandlerBase

from ..exceptions.handling import HandlingException

class RemoveHandler(OutlierHandlerBase):
    """
    Handler to remove rows containing at least one outlier in the selected columns.
    """

    def __init__(
            self,
            columns: Optional[List[str]] = None
    ):
        super().__init__(method = self.__class__.__name__, columns = columns)
    
    def apply(
            self,
            df: pd.DataFrame,
            outlier_mask: Optional[pd.DataFrame] = None
    ) -> pd.DataFrame:
        """
        Deletes rows containing at least one outlier in the selected columns.
        """

        self._validate_input(df = df)

        if outlier_mask is None:
            raise HandlingException(
                error_code="HEX001",
                method=self.method,
                suggestion="The 'remove' method requires an outlier mask generated by a detector."
            )
            
        if not df.index.equals(outlier_mask.index):
            raise HandlingException(
                error_code="HEX001",
                method=self.method,
                suggestion="Index mismatch: DataFrame and outlier_mask must have the same index."
            )
            
        df_clean = df.copy()

        if self.columns is None:
            raise RuntimeError("Validation was done, but self.columns remains None")
        
        # Intersect columns to ensure the mask only operates on valid columns
        valid_cols = [c for c in self.columns if c in outlier_mask.columns]
        
        if not valid_cols:
            # HEX000 equivalent - nothing to handle, return original copy
            return df_clean 
            
        relevant_mask = outlier_mask[valid_cols]
        
        # Keep rows where NO outliers exist in the relevant columns
        return df_clean[~relevant_mask.any(axis=1)]

        